[package]
name                    =  "rsvm"
version                 =  "0.0.1"
description             =  "Rust Virtual Machine"
authors                 = ["Dmitry Ponyatov <dponyatov@gmail.com>"]
license                 =  "MIT"
repository              =  "https://github.com/ponyatov/rsvm"
edition                 =  "2024"

[[bin]]
name                    = "main"
path                    = "src/main.rs"

[[bin]]
name                    = "server"
path                    = "src/server.rs"

[[bin]]
name                    = "linux"
path                    = "src/linux.rs"

[[bin]]
name                    = "f429disco"
path                    = "src/f429disco.rs"

[lib]
name                    =  "librdrs"
path                    =  "src/lib.rs"
crate-type              = ["cdylib"]

[dependencies]
const_format            = "0.2"
nom                     = { version = "8.0", default-features = false}#, features = ["alloc"] }

[target.'cfg(target_os = "linux")'.dependencies]
libc                    = "0.2"
memmap2                 = "0.9"
sdl2                    = {version = "0.38", features = ["ttf","image"], optional = true}

[target.x86_64-unknown-linux-gnu.dependencies]
#xdpilone                = "1.2"

[target.'cfg(target_arch = "arm")'.dependencies]
cortex-m                = "0.7"
cortex-m-rt             = "0.7"
cortex-m-semihosting    = "0.5"
panic-semihosting       = "0.6"
# panic-halt            = "1.0"

stm32f0                 = {version="0.16",optional = true}
stm32f0xx-hal           = {version="0.18",optional = true}
stm32f1                 = {version="0.16",optional = true}
stm32f1xx-hal           = {version="0.10",optional = true}
stm32f4                 = {version="0.16",optional = true}
stm32f4xx-hal           = {version="0.22",optional = true}
stm32l4                 = {version="0.16",optional = true}
stm32l4xx-hal           = {version="0.7" ,optional = true}

[features]
# hw
## x86
pc                      = ["i5"]
qemu386                 = ["i486"]
a7n8x                   = ["i686"]
## rpi
rpi3bp                  = ["bcm2837"]
opi800                  = ["rk3399"]
rpi4                    = ["bcm2711"]
rpi5                    = ["bcm2712"]
## cortexM
pillf030                = ["stm32f030f4"]
pillf103                = ["stm32f103c8"]
lm3s6                   = ["lm3s6965"]
netduino2               = ["stm32f103c8"]
netduinoplus2           = ["stm32f405rg"]
iskra                   = ["stm32f405rg"]
f4disco                 = ["stm32f407vg"]
f429disco               = ["stm32f429zi"]
l496disco               = ["stm32l496ag"]
## esp
esp8266                 = ["lx106"]
esp32                   = ["lx107"]

# cpu
## x86
i486                    = ["i386"]
i686                    = ["i386"]
i5                      = ["x86_64"]
## rpi
bcm2837                 = ["armv7"]
rk3399                  = ["aarch64"]
bcm2711                 = ["aarch64"]
bcm2712                 = ["aarch64"]
## cortexM
stm32f030f4             = ["stm32f0"]
stm32f103c8             = ["stm32f1"]
stm32f405rg             = ["stm32f4"]
stm32f407vg             = ["stm32f4"]
stm32f429zi             = ["stm32f4"]
stm32l496ag             = ["stm32l4"]
stm32f411ce             = ["stm32f4"]
lm3s6965                = ["cortexm3"]
# series
stm32f0                 = ["cortexm0","dep:stm32f0","dep:stm32f0xx-hal"]
stm32f1                 = ["cortexm3","dep:stm32f1","dep:stm32f1xx-hal"]
stm32f4                 = ["cortexm4","dep:stm32f4","dep:stm32f4xx-hal"]
stm32l4                 = ["cortexm4","dep:stm32l4","dep:stm32l4xx-hal"]
## esp
lx106                   = ["xtensa"]
lx107                   = ["xtensa"]

# arch
i386                    = ["linux"]
x86_64                  = ["linux"]
armv7                   = ["linux"]
aarch64                 = ["linux"]
cortexm0                = ["none"]
cortexm3                = ["none"]
cortexm4                = ["none"]
cortexm4f               = ["none"]
xtensa                  = ["freertos"]

# os
none                    = []
linux                   = []
win32                   = []
freertos                = []
rtos8266                = []
idf                     = []
# gui variant
sdl                     = ["dep:sdl2"]
