#!/usr/bin/python3

import datetime
import os as _os
import re
import sys

CWD = _os.getcwd()
MODULE = CWD.split('/')[-1]
ABOUT = sys.argv[1]
AUTHOR = 'Dmitry Ponyatov'
EMAIL = 'dponyatov@gmail.com'
YEAR = datetime.date.today().year
LICENSE = 'MIT'


def add(f): _os.system(f'git add {f}')
def touch(f): open(f, 'a').close(); add(f)
def cp(f): _os.system(f'cp ~/em/{f} {f}'); add(f)


def git():
    _os.system(f'git remote add gh   git@github.com:ponyatov/{MODULE}.git')
    _os.system(f'git remote add flic git@gitflic.ru:dponyatov/{MODULE}.git')
    _os.system('git remote -v')

    def branch(name):
        _os.system(f'git checkout --orphan {name}')
        _os.system('ln -fs ../rc rc')
        add('rc')
        _os.system('git commit -am "."')
        _os.system(f'git push -uv gh {name}')
    branch('dev')
    branch('dponyatov')
    _os.system('git branch -v')


def mkd(d):
    try:
        _os.mkdir(d)
    except FileExistsError:
        pass
    touch(f'{d}/.gitignore')


def rc():
    _os.system('ln -fs ../rc rc && git add rc')


def readme():
    md = 'README.md'
    with open(md, 'w') as f:
        print(f'''# ![](doc/logo.png) `{MODULE}`
## {ABOUT}
\n(c) {AUTHOR} <<{EMAIL}>> {YEAR} {LICENSE}
\n- github:  https://github.com/ponyatov/{MODULE}
- gitflic: https://gitflic.ru/project/dponyatov/{MODULE}''', file=f)
    add(md)


def dirs():
    for d in ['.', '.vscode', 'bin', 'doc', 'lib', 'inc', 'src', 'tmp', 'ref']:
        mkd(d)
    for i in ['bin', 'doc', 'tmp', 'ref']:
        cp(f'{i}/.gitignore')


def giti():
    cp('.gitattributes')
    for i in ['bin', 'ref', 'tmp']:
        with open(f'{i}/.gitignore', 'w') as f:
            print('*', file=f)


HW = {'pc': 'i5', 'pillF103': 'stm32f103c8t', 'f4disco': 'stm32f407vgt'}
CPU = {'i5': 'x86_64', 'stm32f103c8t': 'cortexM3', 'stm32f407vgt': 'cortexM4'}


def hw():
    h = HW.keys()
    mkd('hw')
    for i in h:
        mkd(f'hw/{i}')
        for j in ['inc', 'src']:
            mkd(f'hw/{i}/{j}')
        touch(f'hw/{i}/inc/{i}.hpp')
        touch(f'hw/{i}/src/{i}.cpp')
        for k in ['cmake', 'ocd', 'gdb']:
            touch(f'hw/{i}/{i}.{k}')
        mk = f'hw/{i}/{i}.mk'
        with open(mk, 'w') as m:
            print(f'CPU = {HW[i]}', file=m)
        add(mk)
    mkd('hw/inc')
    mkd('hw/src')
    cp('hw/inc/hw.hpp')


def cpu():
    c = CPU.keys()
    mkd('cpu')
    for i in c:
        mkd(f'cpu/{i}')
        for j in ['inc', 'src']:
            mkd(f'cpu/{i}/{j}')
        touch(f'cpu/{i}/inc/{i}.hpp')
        touch(f'cpu/{i}/src/{i}.cpp')
        cp(f'cpu/{i}/{i}.cmake')
        mk = f'cpu/{i}/{i}.mk'
        with open(mk, 'w') as m:
            print(f'ARCH = {CPU[i]}', file=m)
        add(mk)
    mkd('cpu/inc')
    mkd('cpu/src')
    cp('cpu/inc/cpu.hpp')


ARCH = {'x86_64': 'linux', 'cortexM': 'bare', 'cortexM3': '', 'cortexM4': ''}


def arch():
    mkd('arch')
    for i in ARCH:
        mkd(f'arch/{i}')
        for j in ['inc', 'src']:
            mkd(f'arch/{i}/{j}')
        touch(f'arch/{i}/inc/{i}.hpp')
        touch(f'arch/{i}/src/{i}.cpp')
        cp(f'arch/{i}/{i}.cmake')
        mk = f'arch/{i}/{i}.mk'
        with open(mk, 'w') as m:
            if re.match(r'cortexM\d', i):
                print('include arch/cortexM/cortexM.mk', file=m)
            else:
                print(f'OS = {ARCH[i]}', file=m)
        add(mk)
    mkd('arch/inc')
    mkd('arch/src')
    cp('arch/inc/arch.hpp')


OS = ['linux', 'bare']


def linux():
    cp('os/linux/inc/linux.hpp')
    cp('os/linux/src/linux.cpp')
    cp('os/linux/linux.cmake')


def bare():
    cp('os/bare/inc/bare.hpp')
    cp('os/bare/src/bare.cpp')
    cp('os/bare/bare.cmake')


def os():
    mkd('os')
    for i in OS:
        mkd(f'os/{i}')
        for j in ['inc', 'src']:
            mkd(f'os/{i}/{j}')
        touch(f'os/{i}/inc/{i}.hpp')
        touch(f'os/{i}/src/{i}.cpp')
        touch(f'os/{i}/{i}.cmake')
        touch(f'os/{i}/{i}.mk')
    mkd('os/inc')
    mkd('os/src')
    cp('os/inc/os.hpp')
    cp('os/inc/main.hpp')
    cp('os/src/os.cpp')
    cp('os/src/main.cpp')
    linux()
    bare()


def cross():
    cp('hw/inc/cross.hpp')
    hw()
    cpu()
    arch()
    os()


def mk():
    mkd('mk')
    with open('Makefile', 'w') as m:
        for i in ['var', 'version', 'dirs', 'cross', 'tool',
                  'pkg', 'src', 'cfg',
                  'all', 'clean', 'format', 'rule', 'doc', 'install', 'merge']:
            print(f'include mk/{i}.mk', file=m)
            cp(f'mk/{i}.mk')
    add('Makefile')
    cp('mk/patch.mk')


def presets():
    p = 'CMakePresets.json'
    with open(p, 'w') as f:
        print('''{
    "version": 6,
    "buildPresets": [
        {
            "name"           :   "pillF103",
            "configurePreset":   "pillF103",
            "targets"        :  ["all","install"]
        },
        {
            "name"           :   "f4disco",
            "configurePreset":   "f4disco",
            "targets"        :  ["all","install"]
        },
        {
            "name"           :   "glibc",
            "configurePreset":   "glibc",
            "targets"        :  ["all","install"]
        }
    ],
    "configurePresets": [
        {
            "name"     : "common",
            "hidden"   :  true,
            "binaryDir": "${sourceDir}/tmp/${presetName}",
            "generator": "Unix Makefiles",
            "cacheVariables": {
                "APP"                     : "${workspaceFolderBasename}",
                "CMAKE_INSTALL_PREFIX"    : "${sourceDir}/bin",
                "CMAKE_MODULE_PATH"       : "${sourceDir}/cmake",
                "CMAKE_COLOR_DIAGNOSTICS" : false,
                "CMAKE_BUILD_TYPE"        : "Debug",
                "CMAKE_VERBOSE_MAKEFILE"  : true
            }
        },
        {
            "name"          :  "cortexM",
            "hidden"        :   true,
            "inherits"      :  "common",
            "toolchainFile" :  "${sourceDir}/cmake/arm-none-eabi.cmake",
            "cacheVariables": {"OS":"bare","CMAKE_EXECUTABLE_SUFFIX":".elf"}
        },
        {
            "name"          :  "cortexM0",
            "hidden"        :   true,
            "inherits"      :  "cortexM",
            "cacheVariables": {"ARCH":"cortexM0"}
        },
        {
            "name"          :  "cortexM3",
            "hidden"        :   true,
            "inherits"      :  "cortexM",
            "cacheVariables": {"ARCH":"cortexM3"}
        },
        {
            "name"          :  "cortexM4",
            "hidden"        :   true,
            "inherits"      :  "cortexM",
            "cacheVariables": {"ARCH":"cortexM4"}
        },
        {
            "name"          : "pillF103",
            "inherits"      : "cortexM3",
            "cacheVariables": {
                "HW" :"pillF103",
                "CPU":"stm32f103c8t", "SERIES": "STM32F1"
            }
        },
        {
            "name"          : "f4disco",
            "inherits"      : "cortexM4",
            "cacheVariables": {
                "HW" :"f4disco",
                "CPU":"stm32f407vgt", "SERIES": "STM32F4"
            }
        },
        {
            "name"          : "pc",
            "inherits"      : "common",
            "hidden"        : true,
            "cacheVariables": {
                "HW":"pc", "CPU":"i5", "ARCH":"x86_64"
            }
        },
        {
            "name"          : "linux",
            "inherits"      : "pc",
            "hidden"        : true,
            "cacheVariables": {"OS":"linux"}
        },
       {
            "name"         : "glibc",
            "inherits"     : "linux",
            "displayName"  : "x86_64-linux-gnu",
            "description"  : "native host",
            "toolchainFile": "${sourceDir}/cmake/x86_64-linux-gnu.cmake"
        }
   ]
}''', file=f)
    touch(p)


CMAKE = ['version', 'src', 'syntax', 'FindRAGEL', 'cross', 'clean',
         'any_toolchain',
         'x86_64-linux-gnu',
         'arm-none-eabi'
         ]


def cmake():
    cp('CMakeLists.txt')
    presets()
    mkd('cmake')
    for i in CMAKE:
        cp(f'cmake/{i}.cmake')


def vscode():
    d = '.vscode'
    f = 'settings', 'extensions', 'launch', 'tasks', 'c_cpp_properties'
    mkd(d)
    for i in f:
        cp(f'{d}/{i}.json')


def apt():
    with open(f'apt.Debian', 'w') as d:
        print('''
git make curl
code meld doxygen clang-format
cmake g++ gdb flex bison libreadline-dev ragel
python3 python3-venv python3-ply
gcc-arm-none-eabi    gdb-multiarch qemu-system-arm newlib-source stlink-tools dfu-util dos2unix
'''[1:-1], file=d)
    _os.system('sudo apt update')
    _os.system('sudo apt install -uy `cat apt.Debian`')


# g++-mingw-w64-x86-64 gdb-mingw-w64 wine64 wine64-tools
# gcc-avr avr-libc     gdb-avr       qemu-system-avr
# g++-i686-linux-gnu                 qemu-system-i386
# g++-mingw-w64-i686                 wine32
# docker.io musl-tools
# dotnet-runtime-9.0 dotnet-sdk-9.0
with open(f'apt.Msys', 'w') as d:
    print('''''', file=d)
# git make curl
# cmake mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-gdb
# flex bison libreadline-devel mingw-w64-ucrt-x86_64-ragel
# mingw-w64-ucrt-x86_64-clang-tools-extra


def format():
    for i in ['.clang-format', '.prettierrc']:
        cp(i)


LIB = ['cli', 'core']


def cli():
    open('lib/cli/src/cli.ragel', 'w').close()
    for i in ['hex', 'bin', 'dec', 'oct', 'num']:
        cp(f'lib/cli/src/{i}.ragel')
    for h in ['cli', 'parser']:
        cp(f'lib/cli/inc/{h}.hpp')
    for c in ['cli']:
        cp(f'lib/cli/src/{c}.cpp')
    rl = 'lib/cli/src/cli.ragel'
    with open(rl, 'w') as f:
        print(r'''
#include "os.hpp"
#include "cli.hpp"

%%machine cli;
%%write  data;

static int   cs  = 0;           ///< current state
static int   act = 0;           ///< ???
static char* eof = nullptr;     ///< end of file marker
static char* ts  = nullptr;     ///< token start
static char* te  = nullptr;     ///< token end

void cli(char* p, char* pe) {
    eof = pe; cs = act = 0; ts = te = nullptr;
    %%write init;
    %%write exec;
}

%%{
    comment = '#' [^\n]*;                   # comment
    nl      = '\n';                         # new line
    sp      = [ \r\t]+;                     # drop spaces

    sign    = [+\-];                        # sign
    num     = sign ? digit+ '.' digit+;     # floating point
    dec     = sign ? digit+;                # decimal int
    hex     = "0x" [0-9a-fA-F]+;            # hexadecimal
    oct     = "0o" [0-7]+;                  # octal
    bin     = "0b" [01]+;                   # binary

    id      = [_a-zA-Z][_a-zA-Z0-9]*;       # variable/name

    cli := |*
        comment => { };
        nl+     => { yylineno += te-ts; /* count line */ };
        sp      => { };

        num     => { printf("\t\t%i: num:%f\n",yylineno,num(ts,te)); };
        hex     => { printf("\t\t%i: hex:%x\n",yylineno,hex(ts,te)); };
        oct     => { printf("\t\t%i: oct:%o\n",yylineno,oct(ts,te)); };
        bin     => { printf("\t\t%i: bin:%i\n",yylineno,bin(ts,te)); };
        dec     => { printf("\t\t%i: int:%i\n",yylineno,dec(ts,te)); };

        id      => { printf("\t\t%i:  id:%s\n",yylineno,strndup(ts,te-ts)); };

        any     => { yyerror(strndup(ts,te-ts)); };
    *|;
}%%''', file=f)
    add(rl)


def core():
    for i in ['types']:
        cp(f'lib/core/inc/{i}.hpp')
        cp(f'lib/core/src/{i}.cpp')
    for j in ['object', 'gc',
              'vm', 'cmd',
              'prim', 'int', 'num',
              'cont', 'list', 'map', 'stack',
              'io', 'path', 'dir', 'file',
              'net', 'socket', 'tcp', 'udp', 'mqtt',
              'pin', 'led', 'color',
              'analog', 'block', 'mem', 'dma',
              ]:
        touch(f'lib/core/inc/{j}.hpp')
        touch(f'lib/core/src/{j}.cpp')


def lib():
    mkd('lib')
    mkd('lib/inc')
    touch('lib/inc/lib.hpp')
    mkd('lib/src')
    touch('lib/src/lib.cpp')
    for i in LIB:
        mkd(f'lib/{i}')
        for j in ['inc', 'src']:
            mkd(f'lib/{i}/{j}')
        touch(f'lib/{i}/inc/{i}.hpp')
        touch(f'lib/{i}/src/{i}.cpp')
    cli()
    core()


def app():
    touch('inc/app.hpp')
    touch('src/app.cpp')
    cp('lib/app.ini')


def doxygen():
    with open('../em/.doxygen', 'r') as s:
        s.readline()
        s.readline()
        with open('.doxygen', 'w') as t:
            print(f'PROJECT_NAME           = "{MODULE}"', file=t)
            print(f'PROJECT_BRIEF          = "{ABOUT}"', file=t)
            while True:
                r = s.readline()
                if not r:
                    break
                t.write(r)


def doxy():
    doxygen()
    cp('doc/logo.png')
    cp('doc/DoxygenLayout.xml')


def doc():
    doxy()
    for d in ['cli', 'stm32']:
        mkd(f'doc/{d}')
    for f in ['ByteCode', 'CLI', 'FORTH']:
        cp(f'doc/cli/{f}.md')


PACKS = [git,
         rc, readme,
         dirs, giti, cross, mk, cmake,
         vscode, apt, format, lib, app, doc]


def gen(packs=PACKS):
    for i in packs:
        i()


gen()
# gen(PACKS[1:])
# gen([apt])
