[build]
target    = "x86_64-unknown-linux-gnu"
jobs      = 4

[target.x86_64-unknown-linux-gnu]
rustflags = ["--cfg", "feature=\"pc,i5,linux\""]
linker    = "x86_64-linux-gnu-gcc"

[target.wasm32-unknown-unknown]
linker    = "rust-lld"

[target.aarch64-unknown-linux-gnu]
rustflags = ["--cfg", "feature=\"opi800,linux\""]
linker    = "aarch64-linux-gnu-gcc"

[target.x86_64-pc-windows-gnu]
rustflags = ["--cfg", "feature=\"pc,i5,win64\""]
linker    = "x86_64-w64-mingw32-gcc"

[target.i686-pc-windows-gnu]
rustflags = ["--cfg", "feature=\"pc,i686,mingw32\""]
linker    = "i686-w64-mingw32-gcc"

[target.thumbv7m-none-eabi]
rustflags = ["--cfg", "feature=\"cortexm3\""]
linker    = "arm-none-eabi-gcc"
runner    = [
    'qemu-system-arm',
    '-machine','netduino2','-cpu','cortex-m3',
    '-nographic','-semihosting-config','enable=on,target=native',
    '-s','-S','-kernel'
]
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-nostartfiles",
]

[target.thumbv7em-none-eabihf]
rustflags = ["--cfg", "feature=\"cortexm4\""]
linker    = "arm-none-eabi-gcc"
runner    = [
    'qemu-system-arm',
    '-machine','netduinoplus2','-cpu','cortex-m4',
    '-nographic','-semihosting-config','enable=on,target=native',
    '-s','-S','-kernel'
]
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-nostartfiles",
]

[source.crates-io]
replace-with = 'ustc'

[source.ustc]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"
[source.tuna]
registry = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"
